kem_api_upload:
    pattern: /upload #/{paramName}/{uploadUrl}/{webDir}/{minWidth}/{minHeight}
    defaults: {_controller: "KemImageBundle:Upload:uploadImage"}
    options:
        expose: true

kem_api_crop:
    pattern: /crop #/{uploadUrl}/{webDir}/{imageName}/{x}/{y}/{w}/{h}/{tarW}/{tarH}
    defaults: {_controller: "KemImageBundle:Upload:cropImage"}
    options:
        expose: true

kem_api_image_library:
    pattern: /image-library
    defaults: {_controller: "KemImageBundle:Upload:getLibraryImages"}
    options:
        expose: true